import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    globals: true,
    environment: 'node',
    include: ['src/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: ['src/**'],
      // src/gen is generated by kubb from the OpenAPI spec — testing it would
      // test the generator, not our code. Barrels and type-only files carry no
      // runtime logic (and compile to empty JS, which v8 cannot remap).
      exclude: ['src/gen/**', '**/index.ts', '**/types.ts', '**/*.types.ts'],
      // Hand-written code is fully covered; keep it that way.
      thresholds: { statements: 100, branches: 100, functions: 100, lines: 100 },
    },
  },
})
