import { defineConfig } from 'vitest/config'

import { unitConfig } from '../../vitest.shared.ts'

// src/gen is generated by kubb from the OpenAPI spec — testing it would test
// the generator, not our code. See vitest.shared.ts for everything else.
export default defineConfig(unitConfig({ coverageExclude: ['src/gen/**'] }))
