import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Parses the git-cliff-generated CHANGELOG.md files under packages/*, so the
 * docs site's Changelog page renders the exact same release history that
 * ships in each npm package and in GitHub Releases — same source, same
 * command, so there's structurally no way for the page to drift from them.
 * See docs/adr and .github/actions/release-prepare (the git-cliff invocation
 * these files are generated by).
 */

export interface ChangelogEntry {
  text: string
  author?: string
  prNumber?: number
  prUrl?: string
}

export interface ChangelogGroup {
  title: string
  entries: ChangelogEntry[]
}

export interface ChangelogRelease {
  /** The exact bracket contents from the `## [...]` heading, e.g. "sdk-v3.3.0" or "3.0.1". */
  version: string
  /** Package-prefix stripped for display, e.g. "3.3.0". */
  displayVersion: string
  date?: string
  groups: ChangelogGroup[]
  compareUrl?: string
}

export interface PackageChangelog {
  id: string
  label: string
  releases: ChangelogRelease[]
}

const PACKAGES: { id: string; label: string; dir: string }[] = [
  { id: 'sdk', label: 'marzban-sdk', dir: 'sdk' },
  { id: 'mcp', label: 'marzban-mcp', dir: 'mcp' },
  { id: 'cli', label: 'marzban-cli', dir: 'cli' },
]

const RELEASE_HEADING = /^## \[(.+?)\](?:\s*-\s*(.+))?$/
const GROUP_HEADING = /^### (?:<!--\s*\d+\s*-->)?\s*(.+)$/
const ENTRY_LINE = /^- (.+)$/
const FOOTER_LINK = /^\[([^\]]+)\]:\s*(\S+)/
const PR_SUFFIX = / in \[#(\d+)\]\((\S+)\)$/
const AUTHOR_SUFFIX = / by @([\w.-]+)$/
// git-cliff's "Other" group is dominated by merge-commit housekeeping that
// carries no information for an SDK consumer reading what changed.
const NOISE_ENTRY = /^Merge (pull request #\d+ from|branch) /i

function parseEntry(raw: string): ChangelogEntry {
  let text = raw
  let prNumber: number | undefined
  let prUrl: string | undefined

  const prMatch = text.match(PR_SUFFIX)
  if (prMatch) {
    prNumber = Number(prMatch[1])
    prUrl = prMatch[2]
    text = text.slice(0, prMatch.index).trimEnd()
  }

  let author: string | undefined
  const authorMatch = text.match(AUTHOR_SUFFIX)
  if (authorMatch) {
    author = authorMatch[1]
    text = text.slice(0, authorMatch.index).trimEnd()
  }

  return { text, author, prNumber, prUrl }
}

function stripPackagePrefix(version: string): string {
  return version.replace(/^(sdk|mcp|cli)-v/, '').replace(/^v(?=\d)/, '')
}

/** Parses one git-cliff CHANGELOG.md body into its releases, skipping "Unreleased" and "New Contributors". */
function parseChangelog(raw: string): ChangelogRelease[] {
  const lines = raw.split('\n')
  const releases: ChangelogRelease[] = []
  const compareUrls = new Map<string, string>()
  let release: ChangelogRelease | null = null
  let group: ChangelogGroup | null = null

  for (const line of lines) {
    const footerMatch = line.match(FOOTER_LINK)
    if (footerMatch) {
      compareUrls.set(footerMatch[1], footerMatch[2])
      continue
    }

    const releaseMatch = line.match(RELEASE_HEADING)
    if (releaseMatch) {
      group = null
      if (releaseMatch[1].toLowerCase() === 'unreleased') {
        release = null
        continue
      }
      release = {
        version: releaseMatch[1],
        displayVersion: stripPackagePrefix(releaseMatch[1]),
        date: releaseMatch[2],
        groups: [],
      }
      releases.push(release)
      continue
    }

    if (!release) continue

    const groupMatch = line.match(GROUP_HEADING)
    if (groupMatch) {
      // git-cliff's "New Contributors" section isn't a commit group — skip it,
      // the entries there (e.g. "@user made their first contribution") don't
      // fit the entry-line shape anyway.
      if (groupMatch[1].trim() === 'New Contributors') {
        group = null
        continue
      }
      group = { title: groupMatch[1].trim(), entries: [] }
      release.groups.push(group)
      continue
    }

    if (!group) continue

    const entryMatch = line.match(ENTRY_LINE)
    if (entryMatch && !NOISE_ENTRY.test(entryMatch[1])) group.entries.push(parseEntry(entryMatch[1]))
  }

  for (const r of releases) {
    r.compareUrl = compareUrls.get(r.version)
    r.groups = r.groups.filter(g => g.entries.length > 0)
  }
  return releases.filter(r => r.groups.length > 0)
}

/** All release history for every package, newest release first (already git-cliff's order). */
export function getChangelog(): PackageChangelog[] {
  return PACKAGES.map(pkg => {
    const path = join(process.cwd(), '..', '..', 'packages', pkg.dir, 'CHANGELOG.md')
    let raw: string
    try {
      raw = readFileSync(path, 'utf-8')
    } catch {
      return { id: pkg.id, label: pkg.label, releases: [] }
    }
    return { id: pkg.id, label: pkg.label, releases: parseChangelog(raw) }
  }).filter(pkg => pkg.releases.length > 0)
}
