import { describe, expect, it } from 'vitest'

import { getChangelog, parseChangelog } from './changelog'

/**
 * A trimmed but structurally faithful sample of what cliff.toml's
 * `[changelog]` template produces — the contract this parser depends on. If a
 * change to that template breaks these expectations, the Changelog page would
 * have silently rendered wrong (or empty) instead.
 */
const FIXTURE = `# Changelog

## [Unreleased]

### <!-- 0 -->🚀 Features

- Something not released yet by @Ilmar7786

## [sdk-v3.3.0] - 2026-08-31

### <!-- 1 -->🐛 Bug Fixes

- Tolerate the removeUser 500 that follows a successful delete by @Ilmar7786 ([c7c0c261](https://github.com/Ilmar7786/marzban-sdk/commit/c7c0c261a971a83ed9de7c4f8b01e481f042633a))

### <!-- 10 -->💼 Other

- Potential fix for a CodeQL finding by @Ilmar7786 in [#67](https://github.com/Ilmar7786/marzban-sdk/pull/67) ([5ee0da58](https://github.com/Ilmar7786/marzban-sdk/commit/5ee0da5812345678901234567890123456789012))

### <!-- 2 -->🚜 Refactor

- Read the HTTP status from HttpError instead of digging it out by @Ilmar7786 ([0e9f189f](https://github.com/Ilmar7786/marzban-sdk/commit/0e9f189f58e985b6c8f51bcdac0e59b2b67fcb6b))

### New Contributors

* @someone made their first contribution in [#42](https://github.com/Ilmar7786/marzban-sdk/pull/42)

## [3.0.1] - 2026-06-02

### <!-- 0 -->🚀 Features

- An entry with no author, no PR and no hash

[sdk-v3.3.0]: https://github.com/Ilmar7786/marzban-sdk/compare/sdk-v3.2.0...sdk-v3.3.0
[3.0.1]: https://github.com/Ilmar7786/marzban-sdk/compare/v3.0.0...v3.0.1

<!-- generated by git-cliff -->
`

describe('parseChangelog', () => {
  const releases = parseChangelog(FIXTURE)

  it('skips the Unreleased section', () => {
    expect(releases.map(r => r.version)).toEqual(['sdk-v3.3.0', '3.0.1'])
  })

  it('strips the package prefix for display and keeps the date', () => {
    expect(releases[0].displayVersion).toBe('3.3.0')
    expect(releases[0].date).toBe('2026-08-31')
    expect(releases[1].displayVersion).toBe('3.0.1')
  })

  it("orders groups by git-cliff's numeric sort key, not the file's order", () => {
    // In the file "10" sorts between "1" and "2" — the whole reason the
    // `<!-- N -->` prefix has to be read as a number.
    expect(releases[0].groups.map(g => g.title)).toEqual(['🐛 Bug Fixes', '🚜 Refactor', '💼 Other'])
  })

  it('drops the author suffix and links the commit', () => {
    const [fix] = releases[0].groups[0].entries
    expect(fix.text).toBe('Tolerate the removeUser 500 that follows a successful delete')
    expect(fix.prNumber).toBeUndefined()
    expect(fix.sha).toBe('c7c0c261')
    expect(fix.commitUrl).toBe(
      'https://github.com/Ilmar7786/marzban-sdk/commit/c7c0c261a971a83ed9de7c4f8b01e481f042633a'
    )
  })

  it('handles an entry carrying both a PR link and a hash', () => {
    // Only squash-merged PRs get a PR number (git-cliff matches on
    // merge_commit_sha), so this pair is rare but has to survive both strips.
    const [other] = releases[0].groups[2].entries
    expect(other.text).toBe('Potential fix for a CodeQL finding')
    expect(other.prNumber).toBe(67)
    expect(other.prUrl).toBe('https://github.com/Ilmar7786/marzban-sdk/pull/67')
    expect(other.sha).toBe('5ee0da58')
  })

  it('leaves a pre-hash entry untouched', () => {
    // Everything released before cliff.toml started appending the hash.
    expect(releases[1].groups[0].entries).toEqual([{ text: 'An entry with no author, no PR and no hash' }])
  })

  it('skips the New Contributors section', () => {
    expect(releases[0].groups.map(g => g.title)).not.toContain('New Contributors')
  })

  it('picks up the compare URL from the footer links', () => {
    expect(releases[0].compareUrl).toBe('https://github.com/Ilmar7786/marzban-sdk/compare/sdk-v3.2.0...sdk-v3.3.0')
  })

  it('returns nothing for a changelog with no releases yet', () => {
    expect(parseChangelog('# Changelog\n')).toEqual([])
  })
})

describe('getChangelog', () => {
  it('parses the real committed changelogs', () => {
    // Guards the same invariant as assertParsed(), but at test time: if the
    // real files stop matching the parser, this fails in CI rather than at
    // deploy time.
    const packages = getChangelog()
    const sdk = packages.find(p => p.id === 'sdk')

    expect(sdk?.releases.length).toBeGreaterThan(0)
    expect(sdk?.releases[0].groups.length).toBeGreaterThan(0)
  })
})
