import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

/**
 * Parses the git-cliff-generated CHANGELOG.md files under packages/*, so the
 * docs site's Changelog page renders the same release history that ships in
 * each npm package and in GitHub Releases — one generated source, rendered
 * three ways, with no hand-maintained copy in between.
 *
 * The parser deliberately has NO noise filtering of its own: anything that
 * shouldn't be in the changelog is dropped by cliff.toml's `commit_parsers`,
 * where it also disappears from the npm changelog and the release notes. A
 * filter here would make this page quietly disagree with those two.
 *
 * That makes the shape of these files a contract with cliff.toml's
 * `[changelog] body` template. It's enforced two ways: changelog.test.ts
 * parses a fixture, and `assertParsed()` below fails the build if a file with
 * release headings parses into nothing — a silent, empty Changelog page is
 * the one failure mode worth being loud about.
 *
 * See docs/adr and .github/actions/release-prepare (the git-cliff invocation
 * these files are generated by).
 */

export interface ChangelogEntry {
  text: string
  prNumber?: number
  prUrl?: string
  /** Abbreviated commit hash, e.g. "c7c0c261". */
  sha?: string
  commitUrl?: string
}

export interface ChangelogGroup {
  title: string
  /**
   * git-cliff's sort key, parsed out of the `<!-- N -->` prefix cliff.toml
   * puts on every group name. The prefix exists to order the groups, but it
   * orders them as a *string* — so in the file itself "10" sorts between "1"
   * and "2". Kept as a number here so the page can render the intended order.
   */
  order: number
  entries: ChangelogEntry[]
}

export interface ChangelogRelease {
  /** The exact bracket contents from the `## [...]` heading, e.g. "sdk-v3.3.0" or "3.0.1". */
  version: string
  /** Package-prefix stripped for display, e.g. "3.3.0". */
  displayVersion: string
  date?: string
  groups: ChangelogGroup[]
  compareUrl?: string
}

export interface PackageChangelog {
  id: string
  label: string
  releases: ChangelogRelease[]
}

const PACKAGES: { id: string; label: string; dir: string }[] = [
  { id: 'sdk', label: 'marzban-sdk', dir: 'sdk' },
  { id: 'mcp', label: 'marzban-mcp', dir: 'mcp' },
  { id: 'cli', label: 'marzban-cli', dir: 'cli' },
]

const RELEASE_HEADING = /^## \[(.+?)\](?:\s*-\s*(.+))?$/
const GROUP_HEADING = /^### (?:<!--\s*(\d+)\s*-->)?\s*(.+)$/
const ENTRY_LINE = /^- (.+)$/
const FOOTER_LINK = /^\[([^\]]+)\]:\s*(\S+)/
// Suffixes cliff.toml appends to every entry, stripped back off in the order
// they were added: `<message> [by @author] [in [#pr](url)] ([sha](url))`.
const COMMIT_SUFFIX = / \(\[([0-9a-f]{7,40})\]\((\S+)\)\)$/
const PR_SUFFIX = / in \[#(\d+)\]\((\S+)\)$/
const AUTHOR_SUFFIX = / by @([\w.-]+)$/

function parseEntry(raw: string): ChangelogEntry {
  let text = raw
  let sha: string | undefined
  let commitUrl: string | undefined
  let prNumber: number | undefined
  let prUrl: string | undefined

  // Optional: entries written before cliff.toml started appending the hash
  // (every release up to sdk-v3.3.0) don't have one.
  const commitMatch = text.match(COMMIT_SUFFIX)
  if (commitMatch) {
    sha = commitMatch[1]
    commitUrl = commitMatch[2]
    text = text.slice(0, commitMatch.index).trimEnd()
  }

  const prMatch = text.match(PR_SUFFIX)
  if (prMatch) {
    prNumber = Number(prMatch[1])
    prUrl = prMatch[2]
    text = text.slice(0, prMatch.index).trimEnd()
  }

  // The author is dropped rather than rendered — every entry here carries the
  // same "by @maintainer" tail, and the hash already links to the commit,
  // whose author page is one click away.
  const authorMatch = text.match(AUTHOR_SUFFIX)
  if (authorMatch) text = text.slice(0, authorMatch.index).trimEnd()

  return { text, prNumber, prUrl, sha, commitUrl }
}

function stripPackagePrefix(version: string): string {
  return version.replace(/^(sdk|mcp|cli)-v/, '').replace(/^v(?=\d)/, '')
}

/** Parses one git-cliff CHANGELOG.md body into its releases, skipping "Unreleased" and "New Contributors". */
export function parseChangelog(raw: string): ChangelogRelease[] {
  const lines = raw.split('\n')
  const releases: ChangelogRelease[] = []
  const compareUrls = new Map<string, string>()
  let release: ChangelogRelease | null = null
  let group: ChangelogGroup | null = null

  for (const line of lines) {
    const footerMatch = line.match(FOOTER_LINK)
    if (footerMatch) {
      compareUrls.set(footerMatch[1], footerMatch[2])
      continue
    }

    const releaseMatch = line.match(RELEASE_HEADING)
    if (releaseMatch) {
      group = null
      if (releaseMatch[1].toLowerCase() === 'unreleased') {
        release = null
        continue
      }
      release = {
        version: releaseMatch[1],
        displayVersion: stripPackagePrefix(releaseMatch[1]),
        date: releaseMatch[2],
        groups: [],
      }
      releases.push(release)
      continue
    }

    if (!release) continue

    const groupMatch = line.match(GROUP_HEADING)
    if (groupMatch) {
      // git-cliff's "New Contributors" section isn't a commit group — skip it,
      // the entries there (e.g. "@user made their first contribution") don't
      // fit the entry-line shape anyway.
      if (groupMatch[2].trim() === 'New Contributors') {
        group = null
        continue
      }
      // A group with no `<!-- N -->` prefix predates cliff.toml's current
      // template; sort it last rather than ahead of everything.
      group = { title: groupMatch[2].trim(), order: Number(groupMatch[1] ?? Number.MAX_SAFE_INTEGER), entries: [] }
      release.groups.push(group)
      continue
    }

    if (!group) continue

    const entryMatch = line.match(ENTRY_LINE)
    if (entryMatch) group.entries.push(parseEntry(entryMatch[1]))
  }

  for (const r of releases) {
    r.compareUrl = compareUrls.get(r.version)
    r.groups = r.groups.filter(g => g.entries.length > 0).sort((a, b) => a.order - b.order)
  }
  return releases.filter(r => r.groups.length > 0)
}

/** How many real (non-"Unreleased") release headings the raw file contains. */
function countReleaseHeadings(raw: string): number {
  return raw.split('\n').filter(line => {
    const match = line.match(RELEASE_HEADING)
    return match && match[1].toLowerCase() !== 'unreleased'
  }).length
}

/**
 * Fails the build when a changelog has releases in it but none of them
 * survived parsing — i.e. cliff.toml's template and this parser have drifted
 * apart. A package with no releases yet (a bare `# Changelog`, as marzban-cli
 * has before its first publish) is legitimately empty and just gets skipped.
 */
function assertParsed(pkgDir: string, raw: string, releases: ChangelogRelease[]): void {
  const headings = countReleaseHeadings(raw)
  if (headings > 0 && releases.length === 0) {
    throw new Error(
      `packages/${pkgDir}/CHANGELOG.md has ${headings} release heading(s) but none parsed. ` +
        `cliff.toml's [changelog] body template and apps/docs/src/lib/changelog.ts have drifted apart.`
    )
  }
}

/**
 * Walks up from the working directory to the workspace root (the directory
 * holding pnpm-workspace.yaml). A hardcoded `../..` assumed the build always
 * starts in apps/docs, which is true for `turbo run build` but not for a
 * `next build apps/docs` or a test runner started from the repo root.
 * `import.meta.url` is deliberately not used: the bundled server build moves
 * this module into .next/, where the path no longer sits under apps/docs.
 */
function findRepoRoot(): string {
  let dir = process.cwd()
  for (;;) {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) return dir
    const parent = dirname(dir)
    if (parent === dir)
      throw new Error(`Could not locate the workspace root (no pnpm-workspace.yaml above ${process.cwd()}).`)
    dir = parent
  }
}

/** All release history for every package, newest release first (already git-cliff's order). */
export function getChangelog(): PackageChangelog[] {
  const root = findRepoRoot()

  return PACKAGES.map(pkg => {
    // Committed files, so a missing one is a real problem (a renamed package,
    // a bad checkout) rather than something to render an empty page over.
    const raw = readFileSync(join(root, 'packages', pkg.dir, 'CHANGELOG.md'), 'utf-8')
    const releases = parseChangelog(raw)
    assertParsed(pkg.dir, raw, releases)
    return { id: pkg.id, label: pkg.label, releases }
  }).filter(pkg => pkg.releases.length > 0)
}
